routes/web.php
        Route::get('cpt-generator', [Houston\DashboardController::class, 'cpt_code_generator'])->name('generator.cpt');
        Route::get('signals', [Houston\DashboardController::class, 'signals'])->name('signals');
        Route::get('commands', [Houston\DashboardController::class, 'commands'])->name('commands');
        Route::get('operations', [Houston\DashboardController::class, 'operations'])->name('operations');

        Route::get('roomq', [Houston\DashboardController::class, 'room_search'])->name('roomq');
        Route::get('cptq/{group?}', [Houston\DashboardController::class, 'component_search'])->name('cptq');

        Route::get('tools/mqtt-publisher', [Houston\ToolController::class, 'mqtt_publisher'])->name('tools.mqtt_publisher');
        Route::get('tools/http-poster', [Houston\ToolController::class, 'http_poster'])->name('tools.http_poster');

        Route::get('checklists/type/{type}', [Houston\ChecklistController::class, 'index'])->name('checklists.index.type');
        Route::resource ('checklists', Houston\ChecklistController::class)->only (['index', 'show']);

        Route::get('mia-alerts', [Houston\MIAController::class, 'index'])->name('mia');
    });

    Route::prefix('explore')->name('explorer.')->group(function () {
        Route::get('/', [Explore\ExplorerController::class, 'index'])->name('index');
        Route::resource('operators', Explore\OperatorController::class);
        Route::resource('operators.brands', Explore\BrandController::class);
        Route::resource('operators.brands.properties', Explore\PropertyController::class);
        Route::resource('operators.brands.properties.buildings', Explore\BuildingController::class);
        Route::get('operators/{operator}/brands/{brand}/properties/{property}/buildings/{building}/{floor}', [Explore\RoomController::class, 'index'])->name ('operators.brands.properties.buildings.floor')->where('floor', '[0-9]+');
        Route::get('operators/{operator}/brands/{brand}/properties/{property}/buildings/{building}/{floor}/stickers', [Explore\BuildingController::class, 'stickers'])->name ('operators.brands.properties.buildings.floor.stickers')->where('floor', '[0-9]+');

        Route::prefix('operators/{operator}/brands/{brand}/properties/{property}/buildings/{building}/rooms/{room}')->name('operators.brands.properties.buildings.rooms.')->group(function () {
          Route::get('feed', [Explore\RoomController::class, 'feed'])->name ('feed');
          Route::get('hab', [Explore\RoomController::class, 'hab_availability'])->name ('hab_availability');
          Route::put('hab/provision', [Explore\RoomController::class, 'hab_provisioning'])->name ('hab_provisioning');
          Route::put('hab/deprovision', [Explore\RoomController::class, 'hab_deprovisioning'])->name ('hab_deprovisioning');
          Route::get('hab-config', [Explore\RoomController::class, 'openhab'])->name ('hab_config');
        });

        Route::resource('operators.brands.properties.buildings.rooms', Explore\RoomController::class);

        foreach ([
          'bulbs', 'cameras', 'chromecasts', 'dects', 'dimmers', 'extensions',
          'habs', 'handsets', 'leds', 'locks', 'mirrors', 'motors', 'plugs',
          'routers', 'sensors', 'speakers', 'stbs', 'switches', 'thermostats',
          'tvs', 'wifi-networks'] AS $cpt)
        {

          Route::prefix('operators/{operator}/brands/{brand}/properties/{property}/buildings/{building}/rooms/{room}')->name('operators.brands.properties.buildings.rooms.')->group(function () use ($cpt) {
            Route::get('/'.$cpt.'/{'.Str::singular ($cpt).'}/feed/commands', [Explore\ComponentController::class, 'commands'])->name ($cpt.'.feed.commands');
            Route::get('/'.$cpt.'/{'.Str::singular ($cpt).'}/feed/signals', [Explore\ComponentController::class, 'signals'])->name ($cpt.'.feed.signals');
            Route::put('/'.$cpt.'/provision', [Explore\ComponentController::class, 'provision'])->name ($cpt.'.provision');
            Route::put('/'.$cpt.'/deprovision', [Explore\ComponentController::class, 'deprovision'])->name ($cpt.'.deprovision');
          });

          Route::get('chartdata/daily_commands_chart/'.$cpt.'/{'.Str::singular ($cpt).'}', [Shared\GraphDataController::class, 'component_commands_tput_hourly'])->name('charts.commands_chart.'.Str::singular ($cpt).'.hourly');
          Route::get('chartdata/daily_signals_chart/'.$cpt.'/{'.Str::singular ($cpt).'}', [Shared\GraphDataController::class, 'component_signals_tput_hourly'])->name('charts.signals_chart.'.Str::singular ($cpt).'.hourly');

          Route::get('chartdata/commands_chart/'.$cpt.'/{'.Str::singular ($cpt).'}', [Shared\GraphDataController::class, 'component_commands_tput'])->name('charts.commands_chart.'.Str::singular ($cpt));
          Route::get('chartdata/signals_chart/'.$cpt.'/{'.Str::singular ($cpt).'}', [Shared\GraphDataController::class, 'component_signals_tput'])->name('charts.signals_chart.'.Str::singular ($cpt));

          Route::get('chartdata/attribute_daily_signals_chart/'.$cpt.'/{'.Str::singular ($cpt).'}/{attribute}', [Shared\GraphDataController::class, 'component_signals_attribute_hourly'])->name('charts.attribute_signals_chart.'.Str::singular ($cpt).'.hourly');
          Route::get('chartdata/attribute_daily_commands_chart/'.$cpt.'/{'.Str::singular ($cpt).'}/{attribute}', [Shared\GraphDataController::class, 'component_commands_attribute_hourly'])->name('charts.attribute_commands_chart.'.Str::singular ($cpt).'.hourly');

          Route::get('chartdata/attribute_signals_chart/'.$cpt.'/{'.Str::singular ($cpt).'}/{attribute}', [Shared\GraphDataController::class, 'component_signals_attribute'])->name('charts.attribute_signals_chart.'.Str::singular ($cpt));
          Route::get('chartdata/attribute_commands_chart/'.$cpt.'/{'.Str::singular ($cpt).'}/{attribute}', [Shared\GraphDataController::class, 'component_commands_attribute'])->name('charts.attribute_commands_chart.'.Str::singular ($cpt));

          Route::resource('operators.brands.properties.buildings.rooms.'.$cpt, Explore\ComponentController::class)->except(['index']);

        }
    });

    Route::prefix('idam')->name('idam.')->group(function () {
        Route::get('/', [IDAM\UserController::class, 'index'])->name('index');
        Route::resource('activity', IDAM\ActivityController::class)->only(['index', 'show', 'destroy']);
        Route::resource('permissions', IDAM\PermissionController::class);
        Route::resource('roles', IDAM\RoleController::class);

        Route::get('/users/tagged/{role_tag}', [IDAM\UserController::class, 'index'])->name('users.index.tag');
        Route::resource('users', IDAM\UserController::class);

        Route::resource('users.notes', Shared\NoteController::class);
        Route::resource('users.operators', Shared\OperatorController::class);
        Route::resource('users.permissions', Shared\PermissionController::class);
        Route::resource('users.roles', Shared\RoleController::class);

        Route::get('users/{user}/accesses/{access}/halt', [Shared\AccessController::class, 'halt'])->name('users.accesses.halt');
        Route::resource('users.accesses', Shared\AccessController::class);
    });

    Route::prefix('mirrors')->name('mirrors.')->group(function () {
        Route::get('/', [Mirror\DisplayController::class, 'index'])->name('index');
        Route::resource('displays', Mirror\DisplayController::class);
        Route::get('modules/tagged/{tag?}', [Mirror\ModuleController::class, 'index'])->name('modules.index.tag')->where('tag', '[A-Za-z]+');
        Route::resource('modules', Mirror\ModuleController::class);
    });

    Route::prefix('os')->name('os.')->group(function () {
        Route::get('/', [OS\HABController::class, 'index'])->name('index');
        Route::resource('habs', OS\HABController::class);
        Route::get('mqtt-brokers/{mqtt_broker}/mosquitto', [OS\MQTTBrokerController::class, 'mosquitto_template'])->name('mqtt-brokers.mosquitto');
        Route::get('mqtt-brokers/{mqtt_broker}/env', [OS\MQTTBrokerController::class, 'env_template'])->name('mqtt-brokers.env');
        Route::get('mqtt-brokers/{mqtt_broker}/systemd', [OS\MQTTBrokerController::class, 'systemd_template'])->name('mqtt-brokers.systemd');
        Route::resource('mqtt-brokers', OS\MQTTBrokerController::class);
        Route::get('ws-brokers/{ws_broker}/config', [OS\WSBrokerController::class, 'config_template'])->name('ws-brokers.config');
        Route::get('ws-brokers/{ws_broker}/nginx', [OS\WSBrokerController::class, 'nginx_template'])->name('ws-brokers.nginx');
        Route::resource('ws-brokers', OS\WSBrokerController::class);
        Route::get('vpn-clients/{vpn_client}/revoke', [OS\VPNClientController::class, 'revoke'])->name('vpn-clients.revoke');
        Route::get('vpn-clients/{vpn_client}/unrevoke', [OS\VPNClientController::class, 'unrevoke'])->name('vpn-clients.unrevoke');
        Route::resource('vpn-clients', OS\VPNClientController::class);
        Route::resource('vpn-servers', OS\VPNServerController::class);
    });

    Route::prefix('telecoms')->name('telecoms.')->group(function () {
        Route::get('/', [Telecoms\PBXController::class, 'index'])->name('index');
        Route::resource('pbxs', Telecoms\PBXController::class);
        Route::resource('dect', Telecoms\DECTController::class);
        Route::resource('handsets', Telecoms\HandsetController::class);
        Route::resource('extensions', Telecoms\ExtensionController::class);
    });

    Route::prefix('tvs')->name('tvs.')->group(function () {
        Route::get('/', [TV\STBController::class, 'index'])->name('index');
        Route::resource('stbs', TV\STBController::class);
        Route::get('apps/{tag?}', [TV\AppController::class, 'index'])->name('apps.index');
    });

    Route::prefix('wifi')->name('wifi.')->group(function () {
        Route::get('/', [Wifi\RouterController::class, 'index'])->name('index');

app/Http/Controllers/API/ComfortOS/UserController.php
<?php

namespace SmartRooms\Http\Controllers\API\ComfortOS;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use SmartRooms\Contracts\Repositories\IDAM\UserRepository;
use SmartRooms\Criteria\ComfortOS\UsersAvailableToUserCriteria;
use SmartRooms\Http\Requests\API\ComfortOS\UpdateUser;
use SmartRooms\Models\IDAM\User;

use SmartRooms\Contracts\ComfortOS\UserConstraintManagementContract;

class UserController extends BaseController
{
    public $repository = UserRepository::class;
    public $eager_load = [];
    public $model = User::class;

    public function __construct()
    {
        $this->filter = new UsersAvailableToUserCriteria(auth('api')->user(), $this->model);
    }

    public $constraint_field = 'user_id'; // how ES searches should be limited
    public $constraint = 'users';

    public function update (UpdateUser $request, $model) : JsonResponse
    {
        return $this->__update($request, $model);
    }
}

app/Http/Controllers/Dashboard/IDAM/PermissionController.php
<?php

namespace SmartRooms\Http\Controllers\Dashboard\IDAM;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use SmartRooms\Contracts\Repositories\IDAM\PermissionRepository;
use SmartRooms\Criteria\OrderByCriteria;
use SmartRooms\Http\Controllers\Dashboard\BaseController;

final class PermissionController extends BaseController
{
    public $app_section = 'idam';
    public $nav_section = 'permissions';
    public $repository = PermissionRepository::class;
    public $view_subdir = 'idam.permissions.';

    public function index(Request $request) : View
    {
        try {
            $prepare = app($this->repository)
        ->pushCriteria(new OrderByCriteria('name', 'ASC'));

            return $this->view($this->view_subdir.__FUNCTION__, [
        'records' => $prepare->paginate(25),
      ]);
        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }
}

app/Http/Controllers/Dashboard/IDAM/UserController.php
<?php

namespace SmartRooms\Http\Controllers\Dashboard\IDAM;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\View\View;

use SmartRooms\Http\Controllers\Dashboard\BaseController;
use SmartRooms\Http\Requests\Dashboard\IDAM\StoreUser;

use SmartRooms\Http\Requests\Dashboard\IDAM\UpdateUser;

use SmartRooms\Contracts\Repositories\IDAM\RoleRepository;
use SmartRooms\Contracts\Repositories\IDAM\UserRepository;
use SmartRooms\Contracts\System\UserManagementContract;

use SmartRooms\Criteria\HasRolesCriteria;
use SmartRooms\Criteria\ComfortOS\OtherUsersAvailableToUser;
use SmartRooms\Criteria\OrderByCriteria;
use SmartRooms\Criteria\WhereFieldEqualsCriteria;

use SmartRooms\Models\IDAM\User;

final class UserController extends BaseController
{
    public $app_section = 'idam';
    public $nav_section = 'users';
    public $sub_section = 'basics';
    public $repository = UserRepository::class;
    public $view_subdir = 'idam.users.';

    public function index (Request $request, ?string $tag = null) : View
    {
        $this->authorize (__FUNCTION__, User::class);

        try {

          $records = $this->manager ($request)
            ->with ([
                'roles', 'permissions', 'rooms',
            ]);

          if (! $request->has ('q') )
          {
            $records
              ->pushCriteria (new OrderByCriteria('created_at', 'DESC'))
              ->pushCriteria (new OtherUsersAvailableToUser ($request->user()));

              if ( $tag )
              {
                $records->pushCriteria ( new HasRolesCriteria ([Str::singular($tag)]) );
                $this->nav_section = $tag;
              }
          }

          return $this->view ($this->view_subdir.__FUNCTION__, [
            'records' => $records->paginate(25),
          ]);

        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }

    public function create (Request $request) : View
    {
        $this->authorize (__FUNCTION__, User::class);

        try {

            return $this->view ($this->view_subdir.'create_edit', [

            ]);

        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }

    public function store (Request $request) : View
    {
        $this->authorize (__FUNCTION__, User::class);

        try {

          app (UserManagementContract::class)
              ->dashboard ()
              ->initiator ($request->user())
              ->store ($request->except(['_method', '_token']));

          return redirect()->back()->withInput()->with ('success', 'User created successfully.');

        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }

    public function edit (Request $request, User $user) : View
    {
        $this->authorize (__FUNCTION__, $user);

        try {

            return $this->view ($this->view_subdir.'create_edit', [
              'record' => $user,
            ]);

        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }

    public function update (UpdateUser $request, User $user)
    {
        $this->authorize (__FUNCTION__, $user);

        try {

            app (UserManagementContract::class)
                ->dashboard ()
                ->initiator ($request->user())
                ->entity ($user)
                ->update ($request->except(['_method', '_token']));

            return redirect()->back()->withInput()->with ('success', 'User updated successfully.');

        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }

    public function destroy (Request $request, User $user) : RedirectResponse
    {
        $this->authorize (__FUNCTION__, $user);

        try {

          app (UserManagementContract::class)
            ->dashboard ()
            ->entity ($user)
            ->destroy ();

          return redirect ()->route ('idam.users.index')
            ->with ('success', 'User deleted successfully.');

        } catch (Exception $e) {
            return $this->page_exception_response($e);
        }
    }
}

resources/views/idam/users/permissions/index.blade.php
@extends('layouts.themes.blixy.dashboard')


@section('head')
  <title>SmartRooms:: User Permissions</title>
@stop

@section('app_title')
  <h4>IDAM</h4>
@stop

@section('sidebar')
  @include ('idam.sidebar')
@endsection

@section('header')
  <div class="page-header-container">
      <div class="page-header-main">
          <div class="page-title">Users</div>
          <div class="header-breadcrumb">
              <a href="{{ route('dashboards.index') }}"><i data-feather="user-plus"></i> Home</a>
              <a href="{{ route('idam.index') }}">IDAM</a>
              <a href="{{ route('idam.users.index') }}" class="text-primary">Users</a>
          </div>
      </div>
  </div>
@stop

@section ('content')
  @include ('idam.users.tabs')

  @include ('partials.alerts')

  <div class="main-card mb-3 card">
    <div class="card-body">
      <h5 class="card-title">Manage Individual Permissions</h5>
      <hr />

      <div class="alert alert-bordered-warning mt-3" role="alert">
        These permissions are in addition to those already inherited by the user from their role(s).
      </div>

      {!! Form::open(['route' => ['idam.users.permissions.store', $record->_id]]) !!}

      <div id="accordion" class="accordion mb-3">
        <div class="card">

          @foreach ($permissions->groupBy(function ($item, $key) {
              return \Str::beforeLast ($item->name, '.');
          })->sortKeys() AS $group => $perms)

            <div id="heading-{{ $group }}" class="card-header">
                <a href="javascript:void(0)" data-toggle="collapse" data-target="#{{ $group }}" aria-expanded="false" aria-controls="{{ $group }}" class="text-left m-0 p-0 btn btn-link btn-block collapsed">
                    <h5 class="m-0 p-0 text-dark">{{ $group }}</h5>
                </a>

                  <div class="string-check string-check-bordered-primary string-check-inline pull-right">
                    {!! Form::checkbox ($group.'-all', 1, false, ['id' => $group.'-all', 'class' => 'form-check-input select-all',
                      'onChange' => "toggle_all(this)", 'data-group' => $group,
                      ]) !!}
                  </div>

            </div>
            <div data-parent="#accordion" id="{{ $group }}" aria-labelledby="heading-{{ $group }}" class="collapse show" style="">
                <div class="card-body">
                    <div class="string-check-inline">
                          @foreach ($perms AS $perm)
                            <div class="string-check string-check-bordered-{{ $perm->guard_name == 'web' ? 'primary' : 'warning' }} string-check-inline col-sm-3 col-md-3 mb-2">
                              {!! Form::checkbox ('permissions[]', $perm->_id,
                                in_array ($perm->name, old('permissions', isset($record) ? $record->permissions->pluck('name')->all() : [])) ? true : false,
                                ['id' => $perm->_id, 'class' => 'form-check-input'.($errors->has('permissions.'.$perm->name) ? ' is-invalid' : '')]) !!}
                              <label class="string-check-label text-dark" for="{{ $perm->_id }}"><span class="ml-2">{{ $perm->name }}</span></label>
                            </div>
                          @endforeach
                    </div>
                </div>
            </div>
          @endforeach

        </div>

      </div>


      <hr />

      <div class="row">
        <div class="col-md-6 offset-3">
          {{ $permissions->links() }}
        </div>
      </div>

      <div class="position-relative row form-group mt-3">
        <div class="col-sm-12 text-right">
          @include ('components.buttons.cancel')
          @include ('components.buttons.submit')
        </div>
      </div>

    {!! Form::close() !!}

  </div>
</div>
@stop

@push('js')
  <script type="text/javascript">
    function toggle_all (obj) {
      checkboxes = document.querySelectorAll('#' +obj.getAttribute('data-group')+ ' input')
      for(var i=0, n=checkboxes.length;i<n;i++) {
        checkboxes[i].checked = obj.checked;
      }
    }

  </script>
@endpush